///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class City {
  String? name;
  String? slug;
  String? type;
  String? nameWithType;
  String? code;

  City({
    this.name,
    this.slug,
    this.type,
    this.nameWithType,
    this.code,
  });
  City.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    slug = json['slug']?.toString();
    type = json['type']?.toString();
    nameWithType = json['name_with_type']?.toString();
    code = json['code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['slug'] = slug;
    data['type'] = type;
    data['name_with_type'] = nameWithType;
    data['code'] = code;
    return data;
  }
}

class CityResponse {
  City? the01;

  CityResponse({
    this.the01,
  });
  CityResponse.fromJson(Map<String, dynamic> json) {
    the01 = (json['01'] != null) ? City.fromJson(json['01']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (the01 != null) {
      data['01'] = the01!.toJson();
    }
    return data;
  }
}
