///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Payment {
  int? paymentMethod;
  int? amount;

  Payment({
    this.paymentMethod,
    this.amount,
  });
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['paymentMethod'] = paymentMethod;
    data['amount'] = amount;
    return data;
  }
}

class Address {
  String? detail;
  String? ward;
  String? district;
  String? city;

  Address({
    this.detail,
    this.ward,
    this.district,
    this.city,
  });
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['detail'] = detail;
    data['ward'] = ward;
    data['district'] = district;
    data['city'] = city;
    return data;
  }
}

class CreteJobRequest {
  Address? address;
  Payment? payment;
  String? title;
  String? description;
  List<int?>? categories;
  List<String?>? images;
  List<String?>? videos;
  int? dueDate;

  CreteJobRequest({
    this.address,
    this.payment,
    this.title,
    this.description,
    this.categories,
    this.images,
    this.videos,
    this.dueDate,
  });
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (address != null) {
      data['address'] = address!.toJson();
    }
    data['dueDate'] = dueDate;
    if (payment != null) {
      data['payment'] = payment!.toJson();
    }
    data['title'] = title;
    data['description'] = description;
    if (categories != null) {
      final v = categories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['categories'] = arr0;
    }
    if (images != null) {
      final v = images;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['images'] = arr0;
    }
    if (videos != null) {
      final v = videos;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['videos'] = arr0;
    }
    return data;
  }
}
